### PR TITLE
[popcorntime] v0.3.7.2

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by r1pp3rj4ck** [comment]
thanks, xan

**Comment by xantares** [comment]
no problem :!

**Comment by xantares** [comment]
does it work for you ?

**Comment by r1pp3rj4ck** [comment]
Yea it seems so, why?

**Comment by xantares** [comment]
It did not work right away, I dont understand what happened but it's ok now after a reboot.

**Pull request merged**
